### PR TITLE
sdjournal: allow faster sd-journal api access with a no-op mutex.

### PR DESCRIPTION
**Pull request by glerchundi**

### CODE REVIEW

**Comment by jonboulle** [comment]
before looking at the implementation in detail: can you provide more context? Why would someone want this? Any benchmarks for example?

**Comment by glerchundi** [comment]
The idea is to use this lib for a journald log forwarder i'm working on. It should make the difference under high volume of journaling.

Here the benchmarker
```
$> cat mutex_test.go
package main

import (
  "sync"

  "testing"
)

func BenchmarkMutex(b *testing.B) {
    mu := &sync.Mutex{}
    for i := 0; i < b.N; i++ {
        mu.Lock()
        mu.Unlock()
    }
}

type noOpLocker struct {}

func (*noOpLocker) Lock() {}
func (*noOpLocker) Unlock() {}

func BenchmarkNoOpLocker(b *testing.B) {
    l := &noOpLocker{}
    for i := 0; i < b.N; i++ {
        l.Lock()
        l.Unlock()
    }
}
```

And the results:
```
$> go test -bench=. -benchtime=20s
testing: warning: no tests to run
PASS
BenchmarkMutex-8     	2000000000	        20.2 ns/op
BenchmarkNoOpLocker-8	2000000000	         0.30 ns/op
```

WDYT?

**Comment by crawford** [comment]
A 20ns savings for an operation that is going to take many orders of magnitude longer doesn't seem worth the added complexity.

**Comment by glerchundi** [comment]
Ok, closing this then. I though it was much more...

**Pull request closed without merging**
