### PR TITLE
sdjournal: add GetCatalog

### PR DESCRIPTION
**Pull request by nicorevin**
Just [one](https://www.freedesktop.org/software/systemd/man/sd_journal_get_catalog.html) of the C API methods missing but needed.

### CODE REVIEW

**Comment by lucab** [comment]
Thanks for the PR, @nicorevin! Would you be able to cook a small test for this? It should be possible to look for a custom event (eg. starting a synthetic unit) or just seek to systemd-journald start, and check if the returned catalog message contains some expected keywords.

**Comment by lucab** [comment]
ok to test

**Comment by nicorevin** [comment]
@lucab done!

**Comment by lucab** [comment]
That was quick! LGTM :+1:

**Comment by mheese** [comment]
@nicorevin sweet! :)

**Pull request merged**
