### PR TITLE
sdjournal: add ability to rewind JournalReader

### PR DESCRIPTION
**Pull request by jonboulle**
Simple wrapper around `sd_journal_seek_head`

### CODE REVIEW

**Comment by iaguis** [comment]
To do https://github.com/coreos/rkt/pull/2662/files/4c8103a493c21591f564d4ffa88e9c43d61a5358#r63889264 we need to expose this in `JournalReader` too.

**Comment by jonboulle** [comment]
up day ted

**Comment by jonboulle** [comment]
no

**Comment by iaguis** [comment]
```
iaguis@locke-xps13: ~/work/coreos/go/src/github.com/coreos/go-systemd/sdjournal [(de7d752...)] 
> go test -v .
# github.com/coreos/go-systemd/sdjournal
could not determine kind of name for C.my_sd_journal_seek_head
FAIL	github.com/coreos/go-systemd/sdjournal [build failed]
```

**Comment by jonboulle** [comment]
<- idiot

**Comment by iaguis** [comment]
cgo -> hard

**Comment by jonboulle** [comment]
// char *
  // my_boilerplate()
  // {
  //   char * boiler_plate;
  //   boiler_plate = "dumb";
  //   return boiler_plate;
  // }

**Comment by iaguis** [comment]
lgtm

**Pull request merged**
