### PR TITLE
Add Additional Machined Functions

### PR DESCRIPTION
**Pull request by cpg1111**
This is in regards to issue https://github.com/coreos/go-systemd/issues/213  and I'm aware there was an existing closed PR for this, but I figure this addresses some of those concerns that closed that PR.

### CODE REVIEW

**Comment by cpg1111** [comment]
Tests are failing on a `docker exec`, does anyone happen to have some insight on this?

**Comment by cpg1111** [comment]
So the tests fail due to not running the tests as root, which is required for creating a machine.  Are there any objections to running this as root?

**Comment by jonboulle** [comment]
Could you just move machine1 alongside dbus in the test script? We already only run those if root and this existing non-root machine1 test isn't really doing anything.

**Comment by cpg1111** [comment]
@jonboulle certainly. I just wasn't sure there were already tests running as root. I'll move those shortly.

**Comment by cpg1111** [comment]
Tests are passing now.  I had to add systemd-machined into the containers as a separate package, other than that, all changes are local to the systemd-machined functions.

**Comment by jonboulle** [comment]
@cpg1111 thanks so much! since there was a bit of back and forth with all the commits, I've rebased and made some tweaks and will try to land via #217

**Pull request closed without merging**
