### PR TITLE
dbus: implement support for cgroup freezer APIs

### PR DESCRIPTION
**Pull request by msekletar**

### CODE REVIEW

**Comment by lucab** [comment]
Thanks for the PR.
There is a minimum-version breakage in tests, which I think can be directly massaged here.
Also, I think those are quite recent, so I think our CI here does not cover them yet.
It may be good to add a note in the docstrings about systemd version and cgroup requirements.

**Comment by msekletar** [comment]
I don't think that we should be mentioning systemd version where these APIs where first implemented. Features can (and do get) backported to older versiond and hence our docs would be misleading.

**Comment by msekletar** [comment]
Updated. @lucab PTAL.

**Review by lucab — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
