### PR TITLE
Add in basic login session handling

### PR DESCRIPTION
**Pull request by paultag**
This is far from complete, but I'm starting to sketch out what Session
management could look like from login1.

### CODE REVIEW

**Comment by paultag** [comment]
I'm not sure what action, if any, I need to take

**Comment by lucab** [comment]
My bad, I understood this was a WIP PR at the moment. Anything else you want to add here? If not, I'll go through this next.

**Comment by lucab** [comment]
@paultag ping. What's the status of this? Are you waiting for a review from me or do you have some more bits pending to be queued here?

**Comment by paultag-gov** [comment]
@lucab ach, sorry! I've been hit by a metaphorical bus :)

I'm happy to make changes, but I'm not likely to add more stuff or get around to the tests if need be unless proded, so maybe it's review-able now, and if it's not a fit, we can close this out and move on :)

:+1:

**Comment by paultag** [comment]
@lucab ach, sorry! I've been hit by a metaphorical bus :)

I'm happy to make changes, but I'm not likely to add more stuff or get around to the tests if need be unless proded, so maybe it's review-able now, and if it's not a fit, we can close this out and move on :)

:+1:

**Comment by siavashs** [comment]
I'm interested in this feature, but would like to also add `KillSession()` and `TerminateSession()`, ideally cover [the whole `logind` API](https://www.freedesktop.org/wiki/Software/systemd/logind/).

If @paultag agrees I will take ownership of the PR or open a new one.

**Comment by paultag** [comment]
I absolutely agree! Thank you!

**Comment by paultag** [comment]
Closing in favor of #242

**Pull request closed without merging**
