### PR TITLE
Bump version to v22

### PR DESCRIPTION
**Pull request by saschagrunert**
Here comes the new version which can be released afterwards I guess.

@lucab PTAL

Refers to #307

### CODE REVIEW

**Comment by lucab** [comment]
If everything goes as planned, this shouldn't (hopefully) break the whole world.

I'll proceed to merge and tag this over the weekend. @saschagrunert thanks for your work!

**Comment by saschagrunert** [comment]
You're welcome @lucab :green_heart:

**Comment by lucab** [comment]
I re-triggered one of the travis job, I think it was just a flake.

**Comment by saschagrunert** [comment]
Yes, looks fine now.

**Comment by lucab** [comment]
Tagged: https://github.com/coreos/go-systemd/releases/tag/v22.0.0

**Pull request merged**
