### PR TITLE
dbus: add SystemState method for getting system state

### PR DESCRIPTION
**Pull request by arnested**
Equivalent to `systemctl is-system-running`.

### CODE REVIEW

**Comment by lucab** [comment]
Thanks for the PR! Code looks good, would you mind adding a test to cover this? Just something basic to check that we don't error or panic, and that the resulting property is the string representation for one of the sane states.

**Comment by arnested** [comment]
Cool. I'll add some testing later today or tomorrow!

Thank you.

**Comment by arnested** [comment]
@lucab, please have a look now. I have added a test case.

**Comment by lucab** [comment]
Thanks, LGTM.

**Pull request merged**
